sudo: required
services:
    - docker
env:
    global:
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
    - bash aws-add-eks.sh
install:
    - bash aws-elb-ingress.sh
after_success:
    - bash aws-remove-eks.sh
