sudo: required
services:
    - docker
env:
    global:
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
    - mkdir -p ~/.aws
    - openssl aes-256-cbc -K $encrypted_d506bd5213c4_key -iv $encrypted_d506bd5213c4_iv -in credentials.enc -out ~/.aws/credentials -d
    - openssl aes-256-cbc -K $encrypted_dfba7aade086_key -iv $encrypted_dfba7aade086_iv -in config.enc -out ~/.aws/config -d    
install:
    - travis_wait 30m "bash aws-add-eks.sh setup-aws-eks.yaml"
    - bash aws-elb-ingress.sh setup-aws-eks.yaml
after_success:
    - bash aws-remove-eks.sh setup-aws-eks.yaml
