sudo: required
services:
    - docker
env:
    global:
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
    - docker run alpine/k8s:1.11.10
    - docker cp credentials.enc alpine/k8s:1.11.10:/apps
    - docker cp config.enc alpine/k8s:1.11.10:/apps
    - docker cp setup-aws-eks.yaml alpine/k8s:1.11.10:/apps
    - docker cp aws.sh alpine/k8s:1.11.10:/apps
install:
    - docker exec -it alpine/k8s:1.11.10 /app/aws.sh
after_success:
    - echo "Success"
